CREATE TABLE `t_event` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `gmt_update` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `parent_id` bigint(20) NOT NULL COMMENT '父节点id',
  `app_id` int(11) NOT NULL COMMENT 'appID',
  `app_version` varchar(45) DEFAULT NULL COMMENT 'app版本',
  `event_id` varchar(64) DEFAULT NULL COMMENT '事件定义类型id',
  `module` varchar(64) DEFAULT NULL COMMENT '模块',
  `page` varchar(128) DEFAULT NULL COMMENT '页面',
  `title` varchar(128) DEFAULT NULL COMMENT '显示名称',
  `area_name` varchar(128) DEFAULT NULL COMMENT '区域名称',
  `arg1` varchar(64) DEFAULT NULL,
  `action_name` varchar(128) DEFAULT NULL,
  `args` varchar(2048) DEFAULT NULL,
  `state` int(2) DEFAULT '0' COMMENT '0 老埋点 1 删除 2 新增 3 修改',
  `labels` varchar(128) DEFAULT NULL COMMENT '标签',
  `level` varchar(12) DEFAULT NULL COMMENT '等级',
  `jira_info` varchar(64) DEFAULT NULL COMMENT 'jira数据',
  `android_dev_state` int(2) DEFAULT NULL COMMENT 'android开发状态',
  `ios_dev_state` int(2) DEFAULT NULL COMMENT 'iOS开发状态',
  `android_test_state` int(2) DEFAULT NULL COMMENT 'android测试状态',
  `ios_test_state` int(2) DEFAULT NULL COMMENT 'ios测试状态',
  `remark` varchar(256) DEFAULT NULL COMMENT '备注',
  `extend` text COMMENT '扩展信息',
  `env` varchar(10) DEFAULT NULL COMMENT '环境 daily pre online',
  `event` int(11) DEFAULT NULL COMMENT '事件ID',
  `dev_users` varchar(128) DEFAULT NULL COMMENT '开发用户',
  `test_users` varchar(128) DEFAULT NULL COMMENT '测试用户',
  `owner` varchar(32) DEFAULT NULL COMMENT '事件添加人',
  `page_name` varchar(64) DEFAULT NULL COMMENT '页面昵称',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=36576 DEFAULT CHARSET=utf8